### ISSUE TITLE
Getting an error with svr.owner.id

### ISSUE THREAD

**Issue by Shuttle099** [anandroiduser/AwesomeBot#2]
```
C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\start.js:1527
        var adminList = [svr.owner.id, configs.maintainer, 101496561460060160];
                                  ^

TypeError: Cannot read property 'id' of null
    at defaultConfig (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\start.js:1527:35)
    at Client.<anonymous> (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\start.js:593:13)
    at emitNone (events.js:80:13)
    at Client.emit (events.js:179:7)
    at WebSocket.websocket.onmessage (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\discord.js\lib\Client\InternalClient.js:1345:13)
    at WebSocket.onMessage (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\WebSocket.js:418:14)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onbinary (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\WebSocket.js:823:10)
    at C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\Receiver.js:537:18
    at Receiver.applyExtensions (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\Receiver.js:531:14
    at Receiver.flush (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\Receiver.js:340:3)
    at Receiver.opcodes.2.finish (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\Receiver.js:542:12)
    at Receiver.expectHandler (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\Receiver.js:522:31)
    at Receiver.add (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\Receiver.js:95:24)
    at TLSSocket.realHandler (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:525:20)
```

**Comment by anandroiduser** [comment]
What server is this happening on?

**Comment by Shuttle099** [comment]
When starting up the bot.

**Comment by anandroiduser** [comment]
Yes, but what is the name and member count of the server?

**Comment by Shuttle099** [comment]
The bot is on multiple servers at the time of start.

**Comment by anandroiduser** [comment]
Sure, but that line is in a for loop. The bot only crashes when it reaches a certain server. What is this server?

**Comment by LoganDark2** [comment]
Woooow.
