### ISSUE TITLE
Syntax Error on Line 1767

### ISSUE THREAD

**Issue by Shuttle099** [anandroiduser/AwesomeBot#5]
```
undefined:1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\start.js:1767:34
    at Request.handleRequestResponse [as _callback] (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\unirest\index.js:461:25)
    at Request.self.callback (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\unirest\node_modules\request\request.js:373:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\unirest\node_modules\request\request.js:1318:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (C:\Users\Shuttle099\Desktop\Projects\Apps\SNBot\node_modules\unirest\node_modules\request\request.js:1266:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
```

**Comment by anandroiduser** [comment]
Cannot reproduce. Did you modify how it fetches updates in any way?
